apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: oscap-pipelinerun
spec:
  pipelineRef:
    name: oscap-scan-pipeline
  params:
    - name: xccdfProfile
      value: xccdf_org.ssgproject.content_profile_standard
    - name: oscapProfilePath
      value: /usr/share/xml/scap/ssg/content/ssg-centos7-ds-1.2.xml
    - name: container-imagetag
      value: "latest"